services:

  db:
    container_name: db_test
    image: postgres:17
    environment:
      POSTGRES_DB: apibank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  app:
    build: .
    container_name: order_api
    depends_on:
      - db
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/apibank
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234

      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379

    ports:
      - "8080:8080"

  redis:
    container_name: redis-test
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  postgres_data: