name: Java CI
env:
    APP_NAME: order_api
    DOCKER_USER: xanderg19
on:
  push:
    branches: ["**"]

  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U testuser"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-
            

      - name: Build Java
        run: mvn clean install -Dspring.profiles.active=test

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: app.jar
          path: target/
      - name: test
        run: mvn test
      - name: version java
        run: java --version


  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: target/

      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set tag
        run: echo "TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Build Docker Image
        if: github.ref == 'refs/heads/main'
        run: |
          docker build -t $DOCKER_USER/$APP_NAME:$TAG .
          docker tag $DOCKER_USER/$APP_NAME:$TAG $DOCKER_USER/$APP_NAME:latest

      - name: Push Docker Images
        if: github.ref == 'refs/heads/main'
        run: |
          docker push $DOCKER_USER/$APP_NAME:$TAG
          docker push $DOCKER_USER/$APP_NAME:latest
  info:
    runs-on: ubuntu-latest
    needs: build



    steps:
      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: target/

      - name: info rama
        run: echo $GITHUB_REF

      - name: info commit
        run: echo $GITHUB_SHA

      - name: info sistema
        run: echo $RUNNER_OS

      - name: usuario runner
        run: whoami

      - name: carpeta actual
        run: pwd
      - name: Ver archivos
        run: ls -la

      - name: Ver carpeta target
        run: ls -la target
      - name: variables
        run: echo "ENV=DEV" >> $GITHUB_ENV

      - name: mostrar
        run: echo $ENV
      - name: Nombre workflow
        run: echo ${{ github.workflow}}
      - name: Nombre repo
        run: echo ${{ github.repository }}

      - name: Actor
        run: echo ${{ github.actor }}
      - name: Solo main
        if: github.ref == 'refs/heads/main'
        run: echo "Estoy en main"
      - name: No estoy  main
        if: github.ref != 'refs/heads/main'
        run: echo "No estoy en main"
  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: validar
        run: echo "validar calidad..."




